server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**   #断言,路径相匹配的进行路由
            - After=2017-01-20T17:42:47.789-07:00[Asia/Shanghai]

        - id: payment_routh2
          #uri: http://localhost:8002
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**   #断言,路径相匹配的进行路由
            - After=2017-01-20T17:42:47.789-07:00[Asia/Shanghai]


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka